name = "AlphaShapes"
uuid = "23a43136-1936-4ec7-b2ed-3a5dbec7203f"
authors = ["harveydevereux <harveydevereux@googlemail.com>"]
version = "0.1.1"

[deps]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MiniQhull = "978d7f02-9e05-4691-894f-ae31a51d76ca"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.3.0"
MiniQhull = "0.2.0"
BlackBoxOptim = "0.5.0"
Distances = "0.7.0, 0.9.0"
